export const usersData = [
  { id: '1',  name: 'Amara Okafor',    email: 'amara@example.com',   age: 28, country: 'Nigeria',      status: 'active',   purchases: 14, createdAt: '2023-03-12' },
  { id: '2',  name: 'James Carter',    email: 'james@example.com',   age: 34, country: 'USA',          status: 'active',   purchases: 7,  createdAt: '2022-11-05' },
  { id: '3',  name: 'Fatima Al-Sayed', email: 'fatima@example.com',  age: 22, country: 'Egypt',        status: 'pending',  purchases: 2,  createdAt: '2024-01-20' },
  { id: '4',  name: 'Liam Murphy',     email: 'liam@example.com',    age: 41, country: 'Ireland',      status: 'inactive', purchases: 0,  createdAt: '2021-07-18' },
  { id: '5',  name: 'Yuki Tanaka',     email: 'yuki@example.com',    age: 19, country: 'Japan',        status: 'active',   purchases: 22, createdAt: '2023-09-01' },
  { id: '6',  name: 'Chisom Eze',      email: 'chisom@example.com',  age: 31, country: 'Nigeria',      status: 'active',   purchases: 11, createdAt: '2022-06-30' },
  { id: '7',  name: 'Sofia Rossi',     email: 'sofia@example.com',   age: 27, country: 'Italy',        status: 'pending',  purchases: 3,  createdAt: '2023-12-15' },
  { id: '8',  name: 'Kwame Asante',    email: 'kwame@example.com',   age: 36, country: 'Ghana',        status: 'active',   purchases: 18, createdAt: '2022-04-22' },
  { id: '9',  name: 'Emily Chen',      email: 'emily@example.com',   age: 24, country: 'Canada',       status: 'inactive', purchases: 5,  createdAt: '2023-08-09' },
  { id: '10', name: 'Omar Hassan',     email: 'omar@example.com',    age: 45, country: 'Egypt',        status: 'active',   purchases: 31, createdAt: '2020-02-14' },
  { id: '11', name: 'Priya Sharma',    email: 'priya@example.com',   age: 29, country: 'India',        status: 'active',   purchases: 9,  createdAt: '2023-05-17' },
  { id: '12', name: 'David Osei',      email: 'david@example.com',   age: 17, country: 'Ghana',        status: 'pending',  purchases: 1,  createdAt: '2024-03-01' },
  { id: '13', name: 'Anna Kowalski',   email: 'anna@example.com',    age: 38, country: 'Poland',       status: 'active',   purchases: 25, createdAt: '2021-10-11' },
  { id: '14', name: 'Tunde Adeyemi',   email: 'tunde@example.com',   age: 33, country: 'Nigeria',      status: 'active',   purchases: 16, createdAt: '2022-09-03' },
  { id: '15', name: 'Mei Ling',        email: 'mei@example.com',     age: 26, country: 'China',        status: 'inactive', purchases: 4,  createdAt: '2023-07-28' },
  { id: '16', name: 'Carlos Mendez',   email: 'carlos@example.com',  age: 52, country: 'Mexico',       status: 'active',   purchases: 42, createdAt: '2019-05-20' },
  { id: '17', name: 'Zainab Musa',     email: 'zainab@example.com',  age: 23, country: 'Nigeria',      status: 'pending',  purchases: 0,  createdAt: '2024-02-10' },
  { id: '18', name: 'Henrik Berg',     email: 'henrik@example.com',  age: 44, country: 'Sweden',       status: 'active',   purchases: 13, createdAt: '2021-12-05' },
  { id: '19', name: 'Nia Williams',    email: 'nia@example.com',     age: 20, country: 'UK',           status: 'active',   purchases: 8,  createdAt: '2023-10-22' },
  { id: '20', name: 'Raj Patel',       email: 'raj@example.com',     age: 39, country: 'India',        status: 'inactive', purchases: 6,  createdAt: '2022-03-16' },
  { id: '21', name: 'Blessing Nwosu',  email: 'blessing@example.com',age: 30, country: 'Nigeria',      status: 'active',   purchases: 19, createdAt: '2022-08-07' },
  { id: '22', name: 'Elena Popov',     email: 'elena@example.com',   age: 35, country: 'Russia',       status: 'active',   purchases: 10, createdAt: '2022-01-30' },
  { id: '23', name: 'Seun Alade',      email: 'seun@example.com',    age: 25, country: 'Nigeria',      status: 'pending',  purchases: 2,  createdAt: '2024-01-05' },
  { id: '24', name: 'Tom Fischer',     email: 'tom@example.com',     age: 47, country: 'Germany',      status: 'active',   purchases: 37, createdAt: '2020-06-18' },
  { id: '25', name: 'Aisha Diallo',    email: 'aisha@example.com',   age: 21, country: 'Senegal',      status: 'active',   purchases: 5,  createdAt: '2023-11-14' },
]